/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsRouteImport } from './routes/events'
import { Route as MethodRouteImport } from './routes/method'
import { Route as RoadMapRouteImport } from './routes/road-map'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignalViewerRouteImport } from './routes/signal-viewer'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as TripsRouteImport } from './routes/trips'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadMapRoute = RoadMapRouteImport.update({
  id: '/road-map',
  path: '/road-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalViewerRoute = SignalViewerRouteImport.update({
  id: '/signal-viewer',
  path: '/signal-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/method': typeof MethodRoute
  '/road-map': typeof RoadMapRoute
  '/segments': typeof SegmentsRoute
  '/settings': typeof SettingsRoute
  '/signal-viewer': typeof SignalViewerRoute
  '/trends': typeof TrendsRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/method': typeof MethodRoute
  '/road-map': typeof RoadMapRoute
  '/segments': typeof SegmentsRoute
  '/settings': typeof SettingsRoute
  '/signal-viewer': typeof SignalViewerRoute
  '/trends': typeof TrendsRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/method': typeof MethodRoute
  '/road-map': typeof RoadMapRoute
  '/segments': typeof SegmentsRoute
  '/settings': typeof SettingsRoute
  '/signal-viewer': typeof SignalViewerRoute
  '/trends': typeof TrendsRoute
  '/trips': typeof TripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/method'
    | '/road-map'
    | '/segments'
    | '/settings'
    | '/signal-viewer'
    | '/trends'
    | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/method'
    | '/road-map'
    | '/segments'
    | '/settings'
    | '/signal-viewer'
    | '/trends'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/method'
    | '/road-map'
    | '/segments'
    | '/settings'
    | '/signal-viewer'
    | '/trends'
    | '/trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  MethodRoute: typeof MethodRoute
  RoadMapRoute: typeof RoadMapRoute
  SegmentsRoute: typeof SegmentsRoute
  SettingsRoute: typeof SettingsRoute
  SignalViewerRoute: typeof SignalViewerRoute
  TrendsRoute: typeof TrendsRoute
  TripsRoute: typeof TripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/road-map': {
      id: '/road-map'
      path: '/road-map'
      fullPath: '/road-map'
      preLoaderRoute: typeof RoadMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal-viewer': {
      id: '/signal-viewer'
      path: '/signal-viewer'
      fullPath: '/signal-viewer'
      preLoaderRoute: typeof SignalViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  MethodRoute: MethodRoute,
  RoadMapRoute: RoadMapRoute,
  SegmentsRoute: SegmentsRoute,
  SettingsRoute: SettingsRoute,
  SignalViewerRoute: SignalViewerRoute,
  TrendsRoute: TrendsRoute,
  TripsRoute: TripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
